### ISSUE TITLE
aws ivs

### ISSUE THREAD

**Issue by rajniims** [aws-samples/amazon-ivs-feed-web-demo#3]
How do I get start-time and end-time for Livestream in Amazon Interactive Video Service?
 any API for this

**Comment by slee-aws** [comment]
To get the start and end time of an Amazon IVS stream, you can use AWS Eventbridge to listen to `IVS Stream State Change` events. These events contain information about the state of an IVS stream, including the time of the event:

```
Stream Start event: 
This event is sent when a stream is being processed and segments are available for the viewer
{
   "version": "0",
   "id": "01234567-0123-0123-0123-012345678901",
   "detail-type": "IVS Stream State Change",
   "source": "aws.ivs",
   "account": "aws_account_id",
   "time": "2017-06-12T10:23:43Z",
   "region": "us-east-1",
   "resources": [
     "arn:aws:ivs:us-east-1:aws_account_id:channel/12345678-1a23-4567-a1bc-1a2b34567890"
   ],
   "detail": {
     "event_name": "Stream Start",
     "channel_name": "Your Channel",
     "stream_id": "st-1234EXAMPLE56789"
   }
}
```

For more information, you can visit the user guide: https://docs.aws.amazon.com/ivs/latest/userguide/eventbridge.html

**Comment by slee-aws** [comment]
Hi @rajniims, I just wanted to check if my previous comment answered your question on getting start-time and end-time for an Amazon IVS livestream?
